version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - '5432:5432' # Expose PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./dev.dockerfile
  #   command: CompileDaemon -build="go build -o /build/app" -command="/build/app"
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./:/go/src/app

volumes:
  postgres-data:
